
from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.models.interview import MockInterview
from app.schemas.interview import InterviewCreate, InterviewResponse

router = APIRouter()

@router.post("/interviews", response_model=InterviewResponse)
def create_interview(interview: InterviewCreate, db: Session = Depends(get_db)):
    new_interview = MockInterview(
        interview_type=interview.interview_type,
        user_id=1,          # placeholder — a real user id (test user) for now
        status="in_progress"
    )
    db.add(new_interview)
    db.commit()
    
    '''
    The new_interview object knows interview_type, user_id, and status because 
    I set those. But it does not know its id or started_at because 
    those are generated by the database, not by you
    
    When you db.commit() the databse creates the row and geenrates the id (auto incremenet) and started at. 
    db.refresh(new_interview) goes back to the database and relaods the object, pulling those freshly generated values (id, started_at). 
    '''
    
    db.refresh(new_interview)
    return new_interview