
from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from app.db.database import get_db
from app.models.interview import MockInterview
from app.schemas.interview import InterviewCreate, InterviewResponse

router = APIRouter()

@router.post("/interviews", response_model=InterviewResponse)
def create_interview(interview: InterviewCreate, db: Session = Depends(get_db)):
    new_interview = MockInterview(
        interview_type=interview.interview_type,
        user_id=1,          # placeholder — a real user id (test user) for now
        status="in_progress"
    )
    db.add(new_interview)
    db.commit()
    
    '''
    The new_interview object knows interview_type, user_id, and status because 
    I set those. But it does not know its id or started_at because 
    those are generated by the database, not by you
    
    When you db.commit() the databse creates the row and geenrates the id (auto incremenet) and started at. 
    db.refresh(new_interview) goes back to the database and relaods the object, pulling those freshly generated values (id, started_at). 
    '''
    
    db.refresh(new_interview)
    return new_interview

#def get_learn_topics(db: Session = Depends(get_db)): 

'''
response_model = list[InterviewResponse]
This tells FastAPI what shape the response should be, and it does two jobs:
InterviewReeponse: The schema defining what one interview looks like when sent back as JSON
(id,user_id,interview_type,status,started_at)
list[..]The response is a lsit of those 
#because Get/Interviews returns many interviews 
'''

'''
db.query(MockInterview).all() 
db - your database session (the connection to talk to Postgres, from get_db) 
.query(MockInterview) I want to query the MockInterview table 
.all() give me ALL the rows. IT returns every row in the table 

So the whole line means Using my database session, get all rows from the mock_interviews table. 
It returns a list of MockInterview objects 
One object per row 
So if you have 3 interviews in the table, this returns a list of 3 MockInterview objects each with its id, user_id, and interview)type 
'''


@router.get("/interviews", response_model=list[InterviewResponse])
def get_interviews(db: Session = Depends(get_db)):
    interviews = db.query(MockInterview).all()
    return interviews

@router.patch("/interviews/{interview_id}", response_model=InterviewResponse)
def end_interview(interview_id: int, db: Session = Depends(get_db)):
    interview = db.query(MockInterview).filter(MockInterview.id == interview_id).first()

    if interview is None:
        raise HTTPException(status_code=404, detail="Interview not found")

    interview.status = "completed"
    interview.ended_at = datetime.now(timezone.utc)

    db.commit()
    db.refresh(interview)
    return interview
